Handle external changes better
tasleson/lvm2 pull request #1
Opened 2017-03-08 23:39 UTC by tasleson

Handle external commands better by running query operations through work queue too.

2017-03-08 23:40 UTC, tasleson commented
@vpodzime Please review

2017-03-09 10:50 UTC, vpodzime requested changes
Few things I believe should be changed. But the most important parts of this look good to me. Thanks!

2017-03-09 10:50 UTC, vpodzime commented on daemons/lvmdbusd/manager.py
> +		return '/'
What about logging this as ``debug`` too? That's what I did to debug the issues.

2017-03-09 10:50 UTC, vpodzime commented on daemons/lvmdbusd/utils.py
> +	:param cmdline:
I think this should also specify ``:type cmdline:`` because otherwise it's not easy to determine it from the rest of the documentation here.

2017-03-09 10:50 UTC, vpodzime commented on daemons/lvmdbusd/utils.py
> +		for i in range(0, len(cmdline)):
``for i, arg in enumerate(cmdline)`` would be better here, I think.

2017-03-09 10:50 UTC, vpodzime commented on test/dbus/lvmdbustest.py
> +			std_err_print(
Does this ``std_err_print()`` ever have a chance to execute? AFAIK, ``self.assertTrue`` raises an exception.

2017-03-09 15:47 UTC, tasleson commented on daemons/lvmdbusd/manager.py
> +		return '/'
Yep, will add

2017-03-09 15:47 UTC, tasleson commented on daemons/lvmdbusd/utils.py
> +	:param cmdline:
Yep, will fix thanks!

2017-03-09 15:47 UTC, tasleson commented on daemons/lvmdbusd/utils.py
> +		for i in range(0, len(cmdline)):
Yep, will fix thanks!

2017-03-09 15:47 UTC, tasleson commented on test/dbus/lvmdbustest.py
> +			std_err_print(
Yep, will fix thanks!

2017-03-09 15:47 UTC, tasleson commented
@vpodzime Thanks for the review!

2017-03-09 22:44 UTC, closed without merging